### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\CVPR2019\\data/Training/fake_part/CLKJ_BS1010/06_enm_b.rssdk/depth/151.jpg'

### ISSUE THREAD

**Issue by bingws** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#11]
When I run "python main.py --config="cfgs/fishnet150-32.yaml" --b 32 --lr 0.01 --every-decay 30 --fl-gamma 2 >> fishnet150-train.log". The following error happen:

`D:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main()
  File "main.py", line 198, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 230, in train
    for i, (input, target) in enumerate(train_loader):
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "F:\CVPR2019\read_data.py", line 94, in __getitem__
    depth = Image.open(depth_dir[idx])
  File "D:\ProgramData\Anaconda3\lib\site-packages\PIL\Image.py", line 2609, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\CVPR2019\\data/Training/fake_part/CLKJ_BS1010/06_enm_b.rssdk/depth/151.jpg'`

@SoftwareGift

**Comment by SoftwareGift** [comment]
The file list we provided is suitable for Linux system. According to your error message, it's a path format error.

**Comment by bingws** [comment]
The error also happen on Linux system
![image](https://user-images.githubusercontent.com/10806595/55868427-086cc680-5bb7-11e9-9ba8-a3c69f540322.png)
`root@ubt:/home/ubt/app/CVPR2019# python main.py --config="cfgs/fishnet150-32.yaml" --b 32 --lr 0.01 --every-decay 30 --fl-gamma 2 >> fishnet150-train.log
/root/anaconda3/lib/python3.7/site-packages/torch/nn/modules/upsampling.py:129: UserWarning: nn.Upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.{} is deprecated. Use nn.functional.interpolate instead.".format(self.name))
Traceback (most recent call last):
  File "main.py", line 402, in <module>
    main()
  File "main.py", line 198, in main
    train(train_loader, model, criterion, optimizer, epoch)
  File "main.py", line 230, in train
    for i, (input, target) in enumerate(train_loader):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
FileNotFoundError: Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ubt/app/CVPR2019/read_data.py", line 94, in __getitem__
    depth = Image.open(depth_dir[idx])
  File "/root/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubt/app/CVPR2019/data/Training/fake_part/CLKJ_BS1010/06_enm_b.rssdk/depth/151.jpg'`

@SoftwareGift

**Comment by bingws** [comment]
The error also happen on Linux system
![image](https://user-images.githubusercontent.com/10806595/55868427-086cc680-5bb7-11e9-9ba8-a3c69f540322.png)
@SoftwareGift

**Comment by bingws** [comment]
我发现有个地方的确有问题。我不知道怎么改？
Training文件夹下还是“151_tr.jpg”，而程序似乎要“151.jpg”。
![image](https://user-images.githubusercontent.com/10806595/55875248-33f7ad00-5bc7-11e9-9a9c-23604f363990.png)
“ir_train.txt”下截图可以看出，运行fileList.py后，它是“151.jpg”，如下。
![image](https://user-images.githubusercontent.com/10806595/55875305-60abc480-5bc7-11e9-88bc-0c1006686825.png)
问题应该是这个，我不知道怎么回事。@SoftwareGift

**Comment by bingws** [comment]
@SoftwareGift 看下我的问题，谢谢了。

**Comment by bingws** [comment]
@SoftwareGift 看下我的问题，谢谢了。

**Comment by dandanW91** [comment]
我也遇到了同样的问题，希望您解答一下。

**Comment by xjhjinhui** [comment]
> 我发现有个地方的确有问题。我不知道怎么改？
> Training文件夹下还是“151_tr.jpg”，而程序似乎要“151.jpg”。
> ![image](https://user-images.githubusercontent.com/10806595/55875248-33f7ad00-5bc7-11e9-9a9c-23604f363990.png)
> “ir_train.txt”下截图可以看出，运行fileList.py后，它是“151.jpg”，如下。
> ![image](https://user-images.githubusercontent.com/10806595/55875305-60abc480-5bc7-11e9-88bc-0c1006686825.png)
> 问题应该是这个，我不知道怎么回事。@SoftwareGift

您好，我也遇到了这个问题，请问您最后是如何解决的呢？

**Comment by xjhjinhui** [comment]
> 我发现有个地方的确有问题。我不知道怎么改？
> Training文件夹下还是“151_tr.jpg”，而程序似乎要“151.jpg”。
> ![image](https://user-images.githubusercontent.com/10806595/55875248-33f7ad00-5bc7-11e9-9a9c-23604f363990.png)
> “ir_train.txt”下截图可以看出，运行fileList.py后，它是“151.jpg”，如下。
> ![image](https://user-images.githubusercontent.com/10806595/55875305-60abc480-5bc7-11e9-88bc-0c1006686825.png)
> 问题应该是这个，我不知道怎么回事。@SoftwareGift

我通过rgb.write(pwd + list[0].split('.jpg')[0]+ '_tr' + '.jpg' +'\n')修改了文件名，但是仍然运行不了训练指令，请问您最后是如何解决的呢？
