### ISSUE TITLE
无法使用预训练模型mobilenet_v2.pth.tar

### ISSUE THREAD

**Issue by GQ1011025814** [SoftwareGift/FeatherNets_Face-Anti-spoofing-Attack-Detection-Challenge-CVPR2019#5]
根据您给的百度云盘链接下载的mobilenet_v2.pth.tar无法解压；之前的问题中说不解压也可以使用该模型进行训练，但是仍然是无法使用的，在加载模型时，无法读取该模型的epoch等参数，请问是否是该模型无法使用，能重新上传新的模型吗？
测试命令如下：
python main.py --config="cfgs/mobilenetv2.yaml" --resume ./checkpoints/pre-trainedModels/mobilenet_v2.pth.tar --phase-test True --val True --val-save True
显示如下：
Input image size: 224, test size: 224
  + Number of FLOPs: 306.17M
The network has 2226434 params.
total_params 2226434
D:\FeatherNets_Face-Anti-spoofing-Attack
=> loading checkpoint './checkpoints/pre-trainedModels/mobilenet_v2.pth.tar'
Traceback (most recent call last):
  File "main.py", line 406, in <module>
    main()
  File "main.py", line 151, in main
    args.start_epoch = checkpoint['epoch']
KeyError: 'epoch'

**Comment by SoftwareGift** [comment]
不需要任何解压操作，直接放在指定文件夹加载就可以了，感谢关注！

**Comment by GQ1011025814** [comment]
python main.py --config="cfgs/mobilenetv2.yaml" --resume ./checkpoints/pre-trainedModels/mobilenet_v2.pth.tar --phase-test True --val True --val-save True    没有解压的情况下，输入上述命令的时候，出现args.start_epoch = checkpoint['epoch']    KeyError: 'epoch' 错误，请问是什么原因？

**Comment by SoftwareGift** [comment]
可能你还没有训练导致的，你那个命令是验证并保存预测结果的时候的命令

**Comment by GQ1011025814** [comment]
我是计划不训练，先拿您提供的预训练模型进行测试，验证一下效果与速度，但是根据您提供的测试命令，在加载预训练模型的时候，出现上述的问题。请问我该如何使用该预训练模型进行测试，必须自己重新训练吗？

**Comment by SoftwareGift** [comment]
mobilenet v2的模型不是我自己的，是别人在imagenet上训练的，作为我的模型初始化。暂时还没有开发预训练模型，不好意思。

**Comment by sunjunlishi** [comment]
想知道效果怎么样；可不可以商用？

**Comment by SoftwareGift** [comment]
看应用场景，如果安全级别不是非常高的情况下，是可以用的。模型虽然很小，完全可以实时，但是还需要你有比较好的数据去训练。

**Comment by sunjunlishi** [comment]
你们有没有呀；是否可以提供呀；

**Comment by sunjunlishi** [comment]
要是提供一个小模型，效果还好，要掀起一个雪浪，在嵌入式人脸识别上；

**Comment by SoftwareGift** [comment]
> 你们有没有呀；是否可以提供呀；
有数据是可以达到商用的，时间在10ms左右，预训练模型后期会放出

**Comment by sunjunlishi** [comment]
cool！！

**Comment by huazai-1994** [comment]
可以提供一下训练好的模型吗

**Comment by HulkMaker** [comment]
> mobilenet v2的模型不是我自己的，是别人在imagenet上训练的，作为我的模型初始化。暂时还没有开发预训练模型，不好意思。
你好，请问现在有预训练模型了吗？

**Comment by wwtt666** [comment]
您好，我也遇到了预训练的.pth.tar文件中的参数无法修改的问题，请问您解决了吗？
